### ISSUE TITLE
Not used?

### ISSUE THREAD

**Issue by TeoTN** [fforw/react-inject#1]
Hey, given that you have not released anything for last 5 years, could you please free the name for the package at npmjs ?

**Comment by fforw** [comment]
How do I that?

**Comment by fforw** [comment]
scratch that, I can't.. The package is not mine anymore. It was once published but then I received a takeover notice from "kzantow" who is now listed as maintainer but never published a version 

(Do an "npm view react-inject")

NPM support request number 31846.
